<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Store\Event\Base;

use Store\Event\Module\StoreEvents as ChildStoreEvents;

/*
 * Class StoreEvents
 * @package Store\Event\Base
 * @author TheliaStudio
 */
class StoreEvents
{
    const CREATE = ChildStoreEvents::STORE_CREATE;
    const UPDATE = ChildStoreEvents::STORE_UPDATE;
    const DELETE = ChildStoreEvents::STORE_DELETE;
    const UPDATE_POSITION = ChildStoreEvents::STORE_UPDATE_POSITION;
    const TOGGLE_VISIBILITY = ChildStoreEvents::STORE_TOGGLE_VISIBILITY;
}
