<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Store\Event\Module;

use Store\Event\Module\Base\StoreEvents as BaseStoreEvents;

/**
 * Class StoreEvents
 * @package Store\Event\Module
 * @author TheliaStudio
 */
class StoreEvents extends BaseStoreEvents
{
}
