<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Store\Form;

use Store\Form\Base\StoreUpdateForm as BaseStoreUpdateForm;

/**
 * Class StoreUpdateForm
 * @package Store\Form
 */
class StoreUpdateForm extends BaseStoreUpdateForm
{
    public function getTranslationKeys()
    {
        return array(
            "id" => "id",
            "visible" => "visible",
            "position" => "position",
            "title" => "title",
            "description" => "description",
            "admin_id" => "admin_id",
            "company" => "company",
            "firstname" => "firstname",
            "lastname" => "lastname",
            "address1" => "address1",
            "address2" => "address2",
            "address3" => "address3",
            "zipcode" => "zipcode",
            "city" => "city",
            "phone" => "phone",
            "cellphone" => "cellphone",
            "vat_number" => "vat_number",
            "lat" => "lat",
            "lng" => "lng",
        );
    }
}
