<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Store\Form;

use Store\Form\Base\StoreCreateForm as BaseStoreCreateForm;

/**
 * Class StoreCreateForm
 * @package Store\Form
 */
class StoreCreateForm extends BaseStoreCreateForm
{
    public function getTranslationKeys()
    {
        return array(
            "visible" => "Visible",
            "title" => "Title",
            "description" => "Description",
            "admin_id" => "Admin id",
            "company" => "Company",
            "firstname" => "Firstname",
            "lastname" => "Lastname",
            "address1" => "Address1",
            "address2" => "Address2",
            "address3" => "Address3",
            "zipcode" => "Zipcode",
            "city" => "City",
            "phone" => "Phone",
            "cellphone" => "Cellphone",
            "vat_number" => "Vat number",
            "lat" => "Lat",
            "lng" => "Lng",
        );
    }
}
