<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Store\Action;

use Store\Action\Base\StoreAction as  BaseStoreAction;

/**
 * Class StoreAction
 * @package Store\Action
 */
class StoreAction extends BaseStoreAction
{
}
