<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Store\Event;

use Store\Event\Base\StoreEvents as BaseStoreEvents;

/**
 * Class StoreEvents
 * @package Store\Event
 */
class StoreEvents extends BaseStoreEvents
{
    const STORE_GPS_UPDATE = "action.store.gps.update";

}
