<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Store\Event;

use Store\Event\Base\StoreEvent as BaseStoreEvent;

/**
 * Class StoreEvent
 * @package Store\Event
 */
class StoreEvent extends BaseStoreEvent
{
}
