<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Store\Form\Type\Base;

use Thelia\Core\Form\Type\Field\AbstractIdType;
use Store\Model\StoreQuery;

/**
 * Class Store
 * @package Store\Form\Base
 * @author TheliaStudio
 */
class StoreIdType extends AbstractIdType
{
    const TYPE_NAME = "store_id";

    protected function getQuery()
    {
        return new StoreQuery();
    }

    public function getName()
    {
        return static::TYPE_NAME;
    }
}
