<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Store\Form\Type;

use Store\Form\Type\Base\StoreIdType as BaseStoreIdType;

/**
 * Class Store
 * @package Store\Form
 */
class StoreIdType extends BaseStoreIdType
{
}
