<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Store\Model;

use Store\Model\Base\StoreI18n as BaseStoreI18n;
use Thelia\Model\Tools\I18nTimestampableTrait;

/**
 * Class StoreI18n
 * @package Store\Model
 */
class StoreI18n extends BaseStoreI18n
{
    use I18nTimestampableTrait;
}
