<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Store\Event\Module\Base;

/**
 * Class StoreEvents
 * @package Store\Event\Module\Base
 * @author TheliaStudio
 */
class StoreEvents
{
    const STORE_CREATE = "action.store.create";
    const STORE_UPDATE = "action.store.update";
    const STORE_DELETE = "action.store.delete";
    const STORE_UPDATE_POSITION = "action.store.update_position";
    const STORE_TOGGLE_VISIBILITY = "action.store.toggle_visilibity";
}
