<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Store\Loop;

use Store\Loop\Base\Store as BaseStoreLoop;

/**
 * Class Store
 * @package Store\Loop
 */
class Store extends BaseStoreLoop
{
    /**
     * You may now add your own logic
     */
}
